<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2019-03-11 ( Time 16:43:22 ) -->

<div>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c"    uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="s"    uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fn"   uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt"  uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib tagdir="/WEB-INF/tags/util" prefix="util"%>
<%@ taglib tagdir="/WEB-INF/tags/input" prefix="input"%>

	<div class="container">
		<fieldset class="col-sm-12 bordure">
			<legend class="legende">chapters</legend>
		
	    	<s:url value="${saveAction}" var="url_form_submit" />
			<form:form class="form-horizontal" modelAttribute="chapters" cssClass="well form-horizontal" method="POST" action="${url_form_submit}">
				<form:errors path="*" cssClass="alert alert-danger" element="div" />

<c:if test="${mode != 'create'}">
				<!-- Store data in hidden fields in order to be POST even if the field is disabled -->
				<form:hidden path="chapterId" />
</c:if>


 
				<!-- PRIMARY KEY FIELD : chapterId -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="chapters_chapterId" class="col-sm-2 control-label">chapters.chapterId</label>
					<div class="col-sm-10">
						<form:input id="chapters_chapterId" path="chapterId" class="form-control" disabled="${mode != 'create'}" />
						<form:errors id="chapters_chapterId_errors" path="chapterId" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : bookId -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="chapters_bookId" class="col-sm-2 control-label">chapters.bookId</label>
					<div class="col-sm-10">
  						<form:input id="chapters_bookId" path="bookId" class="form-control" />
						<form:errors id="chapters_bookId_errors" path="bookId" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : title -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="chapters_title" class="col-sm-2 control-label">chapters.title</label>
					<div class="col-sm-10">
  						<form:input id="chapters_title" path="title" class="form-control" />
						<form:errors id="chapters_title_errors" path="title" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : page -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="chapters_page" class="col-sm-2 control-label">chapters.page</label>
					<div class="col-sm-10">
  						<form:input id="chapters_page" path="page" class="form-control" />
						<form:errors id="chapters_page_errors" path="page" cssClass="label label-danger" />

					</div>
				</div>

 

				<!-- ACTION BUTTONS -->
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-2">
						<c:if test="${mode != 'create'}">
							<!-- "DELETE" button ( HREF link ) -->
							<s:url var="deleteButtonURL" value="/chapters/delete/${chapters.chapterId}" />
							<a role="button" class="btn btn-danger btn-block" href="${deleteButtonURL}">delete</a>
						</c:if>
					</div>
    				<div class="col-sm-offset-4 col-sm-2">
						<!-- "CANCEL" button ( HREF link ) -->
		 				<s:url var="cancelButtonURL" value="/chapters" />
						<a role="button" class="btn btn-default btn-block" href="${cancelButtonURL}">cancel</a>
					</div>
    				<div class="col-sm-2">
						<!-- "SAVE" button ( SUBMIT button ) -->
						<button type="submit" class="btn btn-primary btn-lg btn-block">save</button>
					</div>
				</div>
			</form:form>
	    </fieldset>
	</div>	
</div>
