<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2019-03-14 ( Time 13:13:08 ) -->

<div>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c"    uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="s"    uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fn"   uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt"  uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib tagdir="/WEB-INF/tags/util" prefix="util"%>
<%@ taglib tagdir="/WEB-INF/tags/input" prefix="input"%>

	<div class="container">
		<fieldset class="col-sm-12 bordure">
			<legend class="legende">users</legend>
		
	    	<s:url value="${saveAction}" var="url_form_submit" />
			<form:form class="form-horizontal" modelAttribute="users" cssClass="well form-horizontal" method="POST" action="${url_form_submit}">
				<form:errors path="*" cssClass="alert alert-danger" element="div" />

<c:if test="${mode != 'create'}">
				<!-- Store data in hidden fields in order to be POST even if the field is disabled -->
				<form:hidden path="userId" />
</c:if>


 
				<!-- PRIMARY KEY FIELD : userId -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="users_userId" class="col-sm-2 control-label">users.userId</label>
					<div class="col-sm-10">
						<form:input id="users_userId" path="userId" class="form-control" disabled="${mode != 'create'}" />
						<form:errors id="users_userId_errors" path="userId" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : roleId -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="users_roleId" class="col-sm-2 control-label">users.roleId</label>
					<div class="col-sm-10">
  						<form:input id="users_roleId" path="roleId" class="form-control" />
						<form:errors id="users_roleId_errors" path="roleId" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : loginName -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="users_loginName" class="col-sm-2 control-label">users.loginName</label>
					<div class="col-sm-10">
  						<form:input id="users_loginName" path="loginName" class="form-control" />
						<form:errors id="users_loginName_errors" path="loginName" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : password -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="users_password" class="col-sm-2 control-label">users.password</label>
					<div class="col-sm-10">
  						<form:input id="users_password" path="password" class="form-control" />
						<form:errors id="users_password_errors" path="password" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : createdAt -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="users_createdAt" class="col-sm-2 control-label">users.createdAt</label>
					<div class="col-sm-10">
  						<input:date id="users_createdAt" name="createdAt" />  <!-- DATE type -->
						<form:errors id="users_createdAt_errors" path="createdAt" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : deleteFlag -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="users_deleteFlag" class="col-sm-2 control-label">users.deleteFlag</label>
					<div class="col-sm-10">
  						<form:input id="users_deleteFlag" path="deleteFlag" class="form-control" />
						<form:errors id="users_deleteFlag_errors" path="deleteFlag" cssClass="label label-danger" />

					</div>
				</div>

 

				<!-- ACTION BUTTONS -->
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-2">
						<c:if test="${mode != 'create'}">
							<!-- "DELETE" button ( HREF link ) -->
							<s:url var="deleteButtonURL" value="/users/delete/${users.userId}" />
							<a role="button" class="btn btn-danger btn-block" href="${deleteButtonURL}">delete</a>
						</c:if>
					</div>
    				<div class="col-sm-offset-4 col-sm-2">
						<!-- "CANCEL" button ( HREF link ) -->
		 				<s:url var="cancelButtonURL" value="/users" />
						<a role="button" class="btn btn-default btn-block" href="${cancelButtonURL}">cancel</a>
					</div>
    				<div class="col-sm-2">
						<!-- "SAVE" button ( SUBMIT button ) -->
						<button type="submit" class="btn btn-primary btn-lg btn-block">save</button>
					</div>
				</div>
			</form:form>
	    </fieldset>
	</div>	
</div>
