/*
 * Created on 2019-03-11 ( Time 16:43:22 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package com.nit.order_library.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.nit.order_library.bean.Chapters;
import com.nit.order_library.bean.jpa.ChaptersEntity;
import com.nit.order_library.business.service.ChaptersService;
import com.nit.order_library.business.service.mapping.ChaptersServiceMapper;
import com.nit.order_library.data.repository.jpa.ChaptersJpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of ChaptersService
 */
@Component
@Transactional
public class ChaptersServiceImpl implements ChaptersService {

	@Resource
	private ChaptersJpaRepository chaptersJpaRepository;

	@Resource
	private ChaptersServiceMapper chaptersServiceMapper;
	
	@Override
	public Chapters findById(Integer chapterId) {
		ChaptersEntity chaptersEntity = chaptersJpaRepository.findById(chapterId).orElse(null);
		return chaptersServiceMapper.mapChaptersEntityToChapters(chaptersEntity);
	}

	@Override
	public List<Chapters> findAll() {
		Iterable<ChaptersEntity> entities = chaptersJpaRepository.findAll();
		List<Chapters> beans = new ArrayList<Chapters>();
		for(ChaptersEntity chaptersEntity : entities) {
			beans.add(chaptersServiceMapper.mapChaptersEntityToChapters(chaptersEntity));
		}
		return beans;
	}

	@Override
	public Chapters save(Chapters chapters) {
		return update(chapters) ;
	}

	@Override
	public Chapters create(Chapters chapters) {
		ChaptersEntity chaptersEntity;
		if(chapters.getChapterId() != null){
			chaptersEntity = chaptersJpaRepository.findById(chapters.getChapterId()).orElse(null);
			if( chaptersEntity != null ) {
				throw new IllegalStateException("already.exists");
			}
		}
		chaptersEntity = new ChaptersEntity();
		chaptersServiceMapper.mapChaptersToChaptersEntity(chapters, chaptersEntity);
		ChaptersEntity chaptersEntitySaved = chaptersJpaRepository.save(chaptersEntity);
		return chaptersServiceMapper.mapChaptersEntityToChapters(chaptersEntitySaved);
	}

	@Override
	public Chapters update(Chapters chapters) {
		ChaptersEntity chaptersEntity = chaptersJpaRepository.findById(chapters.getChapterId()).orElse(null);
		chaptersServiceMapper.mapChaptersToChaptersEntity(chapters, chaptersEntity);
		ChaptersEntity chaptersEntitySaved = chaptersJpaRepository.save(chaptersEntity);
		return chaptersServiceMapper.mapChaptersEntityToChapters(chaptersEntitySaved);
	}

	@Override
	public void delete(Integer chapterId) {
		chaptersJpaRepository.deleteById(chapterId);
	}

	public ChaptersJpaRepository getChaptersJpaRepository() {
		return chaptersJpaRepository;
	}

	public void setChaptersJpaRepository(ChaptersJpaRepository chaptersJpaRepository) {
		this.chaptersJpaRepository = chaptersJpaRepository;
	}

	public ChaptersServiceMapper getChaptersServiceMapper() {
		return chaptersServiceMapper;
	}

	public void setChaptersServiceMapper(ChaptersServiceMapper chaptersServiceMapper) {
		this.chaptersServiceMapper = chaptersServiceMapper;
	}

}
