<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2021-09-27 ( Time 22:53:19 ) -->

<div>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c"    uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="s"    uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fn"   uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt"  uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib tagdir="/WEB-INF/tags/util" prefix="util"%>
<%@ taglib tagdir="/WEB-INF/tags/input" prefix="input"%>

	<div class="container">
		<fieldset class="col-sm-12 bordure">
			<legend class="legende">orderDataLog</legend>
		
			<form:form class="form-horizontal" modelAttribute="orderDataLog" cssClass="well form-horizontal" method="POST" action="/orderDataLog/update">
				<form:errors path="*" cssClass="alert alert-danger" element="div" />

<c:if test="${mode != 'create'}">
				<!-- Store data in hidden fields in order to be POST even if the field is disabled -->
				<form:hidden path="orderDataLogId" />
</c:if>


 
				<!-- PRIMARY KEY FIELD : orderDataLogId -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="orderDataLog_orderDataLogId" class="col-sm-2 control-label">orderDataLog.orderDataLogId</label>
					<div class="col-sm-10">
						<form:input id="orderDataLog_orderDataLogId" path="orderDataLogId" class="form-control" disabled="${mode != 'create'}" />
						<form:errors id="orderDataLog_orderDataLogId_errors" path="orderDataLogId" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : userId -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="orderDataLog_userId" class="col-sm-2 control-label">orderDataLog.userId</label>
					<div class="col-sm-10">
  						<form:input id="orderDataLog_userId" path="userId" class="form-control" />
						<form:errors id="orderDataLog_userId_errors" path="userId" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : orderId -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="orderDataLog_orderId" class="col-sm-2 control-label">orderDataLog.orderId</label>
					<div class="col-sm-10">
  						<form:input id="orderDataLog_orderId" path="orderId" class="form-control" />
						<form:errors id="orderDataLog_orderId_errors" path="orderId" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : tkind -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="orderDataLog_tkind" class="col-sm-2 control-label">orderDataLog.tkind</label>
					<div class="col-sm-10">
  						<form:input id="orderDataLog_tkind" path="tkind" class="form-control" />
						<form:errors id="orderDataLog_tkind_errors" path="tkind" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : dataType -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="orderDataLog_dataType" class="col-sm-2 control-label">orderDataLog.dataType</label>
					<div class="col-sm-10">
  						<form:input id="orderDataLog_dataType" path="dataType" class="form-control" />
						<form:errors id="orderDataLog_dataType_errors" path="dataType" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : dataTid -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="orderDataLog_dataTid" class="col-sm-2 control-label">orderDataLog.dataTid</label>
					<div class="col-sm-10">
  						<form:input id="orderDataLog_dataTid" path="dataTid" class="form-control" />
						<form:errors id="orderDataLog_dataTid_errors" path="dataTid" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : reqData -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="orderDataLog_reqData" class="col-sm-2 control-label">orderDataLog.reqData</label>
					<div class="col-sm-10">
  						<form:input id="orderDataLog_reqData" path="reqData" class="form-control" />
						<form:errors id="orderDataLog_reqData_errors" path="reqData" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : resData -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="orderDataLog_resData" class="col-sm-2 control-label">orderDataLog.resData</label>
					<div class="col-sm-10">
  						<form:input id="orderDataLog_resData" path="resData" class="form-control" />
						<form:errors id="orderDataLog_resData_errors" path="resData" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : resResultCode -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="orderDataLog_resResultCode" class="col-sm-2 control-label">orderDataLog.resResultCode</label>
					<div class="col-sm-10">
  						<form:input id="orderDataLog_resResultCode" path="resResultCode" class="form-control" />
						<form:errors id="orderDataLog_resResultCode_errors" path="resResultCode" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : resResultMsg -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="orderDataLog_resResultMsg" class="col-sm-2 control-label">orderDataLog.resResultMsg</label>
					<div class="col-sm-10">
  						<form:input id="orderDataLog_resResultMsg" path="resResultMsg" class="form-control" />
						<form:errors id="orderDataLog_resResultMsg_errors" path="resResultMsg" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : reqAt -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="orderDataLog_reqAt" class="col-sm-2 control-label">orderDataLog.reqAt</label>
					<div class="col-sm-10">
  						<input:date id="orderDataLog_reqAt" name="reqAt" />  <!-- DATE type -->
						<form:errors id="orderDataLog_reqAt_errors" path="reqAt" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : resAt -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="orderDataLog_resAt" class="col-sm-2 control-label">orderDataLog.resAt</label>
					<div class="col-sm-10">
  						<input:date id="orderDataLog_resAt" name="resAt" />  <!-- DATE type -->
						<form:errors id="orderDataLog_resAt_errors" path="resAt" cssClass="label label-danger" />

					</div>
				</div>

 

				<!-- ACTION BUTTONS -->
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-2">
						<c:if test="${mode != 'create'}">
							<!-- "DELETE" button ( HREF link ) -->
							<s:url var="deleteButtonURL" value="/orderDataLog/delete/${orderDataLog.orderDataLogId}" />
							<a role="button" class="btn btn-danger btn-block" href="${deleteButtonURL}">delete</a>
						</c:if>
					</div>
    				<div class="col-sm-offset-4 col-sm-2">
						<!-- "CANCEL" button ( HREF link ) -->
		 				<s:url var="cancelButtonURL" value="/orderDataLog" />
						<a role="button" class="btn btn-default btn-block" href="${cancelButtonURL}">cancel</a>
					</div>
    				<div class="col-sm-2">
						<!-- "SAVE" button ( SUBMIT button ) -->
						<button type="submit" class="btn btn-primary btn-lg btn-block">save</button>
					</div>
				</div>
			</form:form>
	    </fieldset>
	</div>	
</div>
