<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2021-09-27 ( Time 22:17:26 ) -->

<div>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c"    uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="s"    uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fn"   uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt"  uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib tagdir="/WEB-INF/tags/util" prefix="util"%>
<%@ taglib tagdir="/WEB-INF/tags/input" prefix="input"%>

	<div class="container">
		<fieldset class="col-sm-12 bordure">
			<legend class="legende">adidInfo</legend>
		
	    	<s:url value="${saveAction}" var="url_form_submit" />
			<form:form class="form-horizontal" modelAttribute="adidInfo" cssClass="well form-horizontal" method="POST" action="${url_form_submit}">
				<form:errors path="*" cssClass="alert alert-danger" element="div" />

<c:if test="${mode != 'create'}">
				<!-- Store data in hidden fields in order to be POST even if the field is disabled -->
				<form:hidden path="adidInfoId" />
</c:if>


 
				<!-- PRIMARY KEY FIELD : adidInfoId -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="adidInfo_adidInfoId" class="col-sm-2 control-label">adidInfo.adidInfoId</label>
					<div class="col-sm-10">
						<form:input id="adidInfo_adidInfoId" path="adidInfoId" class="form-control" disabled="${mode != 'create'}" />
						<form:errors id="adidInfo_adidInfoId_errors" path="adidInfoId" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : userId -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="adidInfo_userId" class="col-sm-2 control-label">adidInfo.userId</label>
					<div class="col-sm-10">
  						<form:input id="adidInfo_userId" path="userId" class="form-control" />
						<form:errors id="adidInfo_userId_errors" path="userId" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : adid -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="adidInfo_adid" class="col-sm-2 control-label">adidInfo.adid</label>
					<div class="col-sm-10">
  						<form:input id="adidInfo_adid" path="adid" class="form-control" />
						<form:errors id="adidInfo_adid_errors" path="adid" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : deviceKind -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="adidInfo_deviceKind" class="col-sm-2 control-label">adidInfo.deviceKind</label>
					<div class="col-sm-10">
  						<form:input id="adidInfo_deviceKind" path="deviceKind" class="form-control" />
						<form:errors id="adidInfo_deviceKind_errors" path="deviceKind" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : validYn -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="adidInfo_validYn" class="col-sm-2 control-label">adidInfo.validYn</label>
					<div class="col-sm-10">
  						<form:input id="adidInfo_validYn" path="validYn" class="form-control" />
						<form:errors id="adidInfo_validYn_errors" path="validYn" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : createdAt -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="adidInfo_createdAt" class="col-sm-2 control-label">adidInfo.createdAt</label>
					<div class="col-sm-10">
  						<input:date id="adidInfo_createdAt" name="createdAt" />  <!-- DATE type -->
						<form:errors id="adidInfo_createdAt_errors" path="createdAt" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : updatedAt -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="adidInfo_updatedAt" class="col-sm-2 control-label">adidInfo.updatedAt</label>
					<div class="col-sm-10">
  						<input:date id="adidInfo_updatedAt" name="updatedAt" />  <!-- DATE type -->
						<form:errors id="adidInfo_updatedAt_errors" path="updatedAt" cssClass="label label-danger" />

					</div>
				</div>

 

				<!-- ACTION BUTTONS -->
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-2">
						<c:if test="${mode != 'create'}">
							<!-- "DELETE" button ( HREF link ) -->
							<s:url var="deleteButtonURL" value="/adidInfo/delete/${adidInfo.adidInfoId}" />
							<a role="button" class="btn btn-danger btn-block" href="${deleteButtonURL}">delete</a>
						</c:if>
					</div>
    				<div class="col-sm-offset-4 col-sm-2">
						<!-- "CANCEL" button ( HREF link ) -->
		 				<s:url var="cancelButtonURL" value="/adidInfo" />
						<a role="button" class="btn btn-default btn-block" href="${cancelButtonURL}">cancel</a>
					</div>
    				<div class="col-sm-2">
						<!-- "SAVE" button ( SUBMIT button ) -->
						<button type="submit" class="btn btn-primary btn-lg btn-block">save</button>
					</div>
				</div>
			</form:form>
	    </fieldset>
	</div>	
</div>
