<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2019-03-11 ( Time 16:43:21 ) -->

<div>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c"    uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="s"    uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fn"   uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt"  uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib tagdir="/WEB-INF/tags/util" prefix="util"%>
<%@ taglib tagdir="/WEB-INF/tags/input" prefix="input"%>

	<div class="container">
		<fieldset class="col-sm-12 bordure">
			<legend class="legende">books</legend>
		
	    	<s:url value="${saveAction}" var="url_form_submit" />
			<form:form class="form-horizontal" modelAttribute="books" cssClass="well form-horizontal" method="POST" action="${url_form_submit}">
				<form:errors path="*" cssClass="alert alert-danger" element="div" />

<c:if test="${mode != 'create'}">
				<!-- Store data in hidden fields in order to be POST even if the field is disabled -->
				<form:hidden path="bookId" />
</c:if>


 
				<!-- PRIMARY KEY FIELD : bookId -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="books_bookId" class="col-sm-2 control-label">books.bookId</label>
					<div class="col-sm-10">
						<form:input id="books_bookId" path="bookId" class="form-control" disabled="${mode != 'create'}" />
						<form:errors id="books_bookId_errors" path="bookId" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : name -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="books_name" class="col-sm-2 control-label">books.name</label>
					<div class="col-sm-10">
  						<form:input id="books_name" path="name" class="form-control" />
						<form:errors id="books_name_errors" path="name" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : author -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="books_author" class="col-sm-2 control-label">books.author</label>
					<div class="col-sm-10">
  						<form:input id="books_author" path="author" class="form-control" />
						<form:errors id="books_author_errors" path="author" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : publishDate -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="books_publishDate" class="col-sm-2 control-label">books.publishDate</label>
					<div class="col-sm-10">
  						<input:date id="books_publishDate" name="publishDate" />  <!-- DATE type -->
						<form:errors id="books_publishDate_errors" path="publishDate" cssClass="label label-danger" />

					</div>
				</div>



 
				<!-- DATA FIELD : description -->
				<div class="form-group">
					<!-- The field label is defined in the messages file (for i18n) -->
					<label for="books_description" class="col-sm-2 control-label">books.description</label>
					<div class="col-sm-10">
  						<form:input id="books_description" path="description" class="form-control" />
						<form:errors id="books_description_errors" path="description" cssClass="label label-danger" />

					</div>
				</div>

 

				<!-- ACTION BUTTONS -->
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-2">
						<c:if test="${mode != 'create'}">
							<!-- "DELETE" button ( HREF link ) -->
							<s:url var="deleteButtonURL" value="/books/delete/${books.bookId}" />
							<a role="button" class="btn btn-danger btn-block" href="${deleteButtonURL}">delete</a>
						</c:if>
					</div>
    				<div class="col-sm-offset-4 col-sm-2">
						<!-- "CANCEL" button ( HREF link ) -->
		 				<s:url var="cancelButtonURL" value="/books" />
						<a role="button" class="btn btn-default btn-block" href="${cancelButtonURL}">cancel</a>
					</div>
    				<div class="col-sm-2">
						<!-- "SAVE" button ( SUBMIT button ) -->
						<button type="submit" class="btn btn-primary btn-lg btn-block">save</button>
					</div>
				</div>
			</form:form>
	    </fieldset>
	</div>	
</div>
