/*
 * Created on 2019-03-11 ( Time 16:43:21 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package com.nit.order_library.web.controller;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import com.nit.order_library.web.common.AbstractController;
import com.nit.order_library.web.common.FormMode;
//import com.nit.order_library.web.common.Message;
//import com.nit.order_library.web.common.MessageType;

//--- Entities
import com.nit.order_library.bean.Books;

//--- Services 
import com.nit.order_library.business.service.BooksService;

/**
 * Spring MVC controller for 'Books' management.
 */
@Controller
@RequestMapping("/books")
public class BooksController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "books";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "books/form";
	private static final String JSP_LIST   = "books/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/books/create";
	private static final String SAVE_ACTION_UPDATE   = "/books/update";

	//--- Main entity service
	@Resource
    private BooksService booksService; // Injected by Spring
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public BooksController() {
		super(BooksController.class, MAIN_ENTITY_NAME );
		log("BooksController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------

	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param books
	 */
	private void populateModel(Model model, Books books, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, books);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Books found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Books> list = booksService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new Books
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Books books = new Books();	
		populateModel( model, books, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Books
	 * @param model Spring MVC model
	 * @param bookId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{bookId}")
	public String formForUpdate(Model model, @PathVariable("bookId") Integer bookId ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Books books = booksService.findById(bookId);
		populateModel( model, books, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param books  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Books books, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Books booksCreated = booksService.create(books); 
				model.addAttribute(MAIN_ENTITY_NAME, booksCreated);

				//---
				return redirectToForm(httpServletRequest, books.getBookId() );
			} else {
				populateModel( model, books, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			populateModel( model, books, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param books  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Books books, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Books booksSaved = booksService.update(books);
				model.addAttribute(MAIN_ENTITY_NAME, booksSaved);
				//--- Set the result message
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, books.getBookId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, books, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, books, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param bookId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{bookId}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("bookId") Integer bookId) {
		log("Action 'delete'" );
		try {
			booksService.delete( bookId );
			//--- Set the result message
		} catch(Exception e) {
		}
		return redirectToList();
	}

}
