/*
 * Created on 2019-03-14 ( Time 16:44:08 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package com.nit.order_library.web.controller;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import com.nit.order_library.web.common.AbstractController;
import com.nit.order_library.web.common.FormMode;
//import com.nit.order_library.web.common.Message;
//import com.nit.order_library.web.common.MessageType;

//--- Entities
import com.nit.order_library.bean.Members;
import com.nit.order_library.bean.Roles;
//--- Services 
import com.nit.order_library.business.service.MembersService;

/**
 * Spring MVC controller for 'Members' management.
 */
@Controller
@RequestMapping("/members")
public class MembersController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "members";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "members/form";
	private static final String JSP_LIST   = "members/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/members/create";
	private static final String SAVE_ACTION_UPDATE   = "/members/update";

	//--- Main entity service
	@Resource
    private MembersService membersService; // Injected by Spring
	//--- Other service(s)
	
	@Autowired
	private PasswordEncoder passwordEncoder;
	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public MembersController() {
		super(MembersController.class, MAIN_ENTITY_NAME );
		log("MembersController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------

	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param members
	 */
	private void populateModel(Model model, Members members, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, members);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Members found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Members> list = membersService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new Members
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Members members = new Members();	
		populateModel( model, members, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Members
	 * @param model Spring MVC model
	 * @param userId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{userId}")
	public String formForUpdate(Model model, @PathVariable("userId") Integer userId ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Members members = membersService.findById(userId);
		populateModel( model, members, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param members  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Members members, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				
				Roles role = new Roles();
				role.setRoleName("ADMIN");
				members.setPassword(passwordEncoder.encode(members.getPassword()));
				Members membersCreated = membersService.create(members, role); 
				model.addAttribute(MAIN_ENTITY_NAME, membersCreated);

				//---
				return redirectToForm(httpServletRequest, members.getUserId() );
			} else {
				populateModel( model, members, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			populateModel( model, members, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param members  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Members members, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				members.setPassword(passwordEncoder.encode(members.getPassword()));
				
				Members membersSaved = membersService.update(members);
				model.addAttribute(MAIN_ENTITY_NAME, membersSaved);
				//--- Set the result message
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, members.getUserId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, members, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, members, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param userId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{userId}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("userId") Integer userId) {
		log("Action 'delete'" );
		try {
			membersService.delete( userId );
			//--- Set the result message
		} catch(Exception e) {
		}
		return redirectToList();
	}

}
