/*
 * Created on 2019-03-11 ( Time 16:43:22 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package com.nit.order_library.business.service;

import java.util.List;
import org.springframework.stereotype.Service;

import com.nit.order_library.bean.Books;

/**
 * Business Service Interface for entity Books.
 */
@Service
public interface BooksService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param bookId
	 * @return entity
	 */
	Books findById( Integer bookId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Books> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Books save(Books entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Books update(Books entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Books create(Books entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param bookId
	 */
	void delete( Integer bookId );


}
