/*
 * Created on 2019-03-11 ( Time 16:43:22 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package com.nit.order_library.business.service;

import java.util.List;
import org.springframework.stereotype.Service;

import com.nit.order_library.bean.Chapters;

/**
 * Business Service Interface for entity Chapters.
 */
@Service
public interface ChaptersService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param chapterId
	 * @return entity
	 */
	Chapters findById( Integer chapterId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Chapters> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Chapters save(Chapters entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Chapters update(Chapters entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Chapters create(Chapters entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param chapterId
	 */
	void delete( Integer chapterId );


}
