/*
 * Created on 2019-03-14 ( Time 16:44:08 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package com.nit.order_library.business.service;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.nit.order_library.bean.Members;
import com.nit.order_library.bean.Roles;
import com.nit.order_library.bean.jpa.MembersEntity;
import com.nit.order_library.bean.jpa.RolesEntity;
import com.nit.order_library.business.service.mapping.MembersServiceMapper;
import com.nit.order_library.business.service.mapping.RolesServiceMapper;
import com.nit.order_library.data.repository.jpa.MembersJpaRepository;
import com.nit.order_library.data.repository.jpa.RolesJpaRepository;

/**
 * Definition of MembersService
 */
@Service
@Transactional
public class MembersService {

	@Resource
	private MembersJpaRepository membersJpaRepository;

	@Resource
	private MembersServiceMapper membersServiceMapper;
	
	@Resource
	private RolesJpaRepository rolesJpaRepository;

	@Resource
	private RolesServiceMapper rolesServiceMapper;
	
	public Members findById(Integer userId) {
		MembersEntity membersEntity = membersJpaRepository.findById(userId).orElse(null);
		return membersServiceMapper.mapMembersEntityToMembers(membersEntity);
	}

	public List<Members> findAll() {
		Iterable<MembersEntity> entities = membersJpaRepository.findAll();
		List<Members> beans = new ArrayList<Members>();
		for(MembersEntity membersEntity : entities) {
			beans.add(membersServiceMapper.mapMembersEntityToMembers(membersEntity));
		}
		return beans;
	}

	public Members save(Members members) {
		return update(members) ;
	}

	public Members create(Members members, Roles role) {
		MembersEntity membersEntity;
		if(members.getUserId() != null){
			membersEntity = membersJpaRepository.findById(members.getUserId()).orElse(null);
			if( membersEntity != null ) {
				throw new IllegalStateException("already.exists");
			}
		}
		
		membersEntity = new MembersEntity();
		membersServiceMapper.mapMembersToMembersEntity(members, membersEntity);
		MembersEntity membersEntitySaved = membersJpaRepository.save(membersEntity);
		role.setUserId(membersEntitySaved.getUserId());
		RolesEntity rolesEntity = new RolesEntity();
		rolesServiceMapper.mapRolesToRolesEntity(role, rolesEntity);
		rolesJpaRepository.save(rolesEntity);
				
		return membersServiceMapper.mapMembersEntityToMembers(membersEntitySaved);
	}

	public Members update(Members members) {
		MembersEntity membersEntity = membersJpaRepository.findById(members.getUserId()).orElse(null);
		membersServiceMapper.mapMembersToMembersEntity(members, membersEntity);
		MembersEntity membersEntitySaved = membersJpaRepository.save(membersEntity);
		return membersServiceMapper.mapMembersEntityToMembers(membersEntitySaved);
	}

	public void delete(Integer userId) {
		membersJpaRepository.deleteById(userId);
	}

	public MembersJpaRepository getMembersJpaRepository() {
		return membersJpaRepository;
	}

	public void setMembersJpaRepository(MembersJpaRepository membersJpaRepository) {
		this.membersJpaRepository = membersJpaRepository;
	}

	public MembersServiceMapper getMembersServiceMapper() {
		return membersServiceMapper;
	}

	public void setMembersServiceMapper(MembersServiceMapper membersServiceMapper) {
		this.membersServiceMapper = membersServiceMapper;
	}

}
