/*
 * Created on 2019-03-14 ( Time 16:44:08 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package com.nit.order_library.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.nit.order_library.bean.Chapters;
import com.nit.order_library.bean.jpa.ChaptersEntity;
import com.nit.order_library.bean.jpa.BooksEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ChaptersServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ChaptersServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ChaptersEntity' to 'Chapters'
	 * @param chaptersEntity
	 */
	public Chapters mapChaptersEntityToChapters(ChaptersEntity chaptersEntity) {
		if(chaptersEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Chapters chapters = map(chaptersEntity, Chapters.class);

		//--- Link mapping ( link to Books )
		if(chaptersEntity.getBooks() != null) {
			chapters.setBookId(chaptersEntity.getBooks().getBookId());
		}
		return chapters;
	}
	
	/**
	 * Mapping from 'Chapters' to 'ChaptersEntity'
	 * @param chapters
	 * @param chaptersEntity
	 */
	public void mapChaptersToChaptersEntity(Chapters chapters, ChaptersEntity chaptersEntity) {
		if(chapters == null) {
			return;
		}

		//--- Generic mapping 
		map(chapters, chaptersEntity);

		//--- Link mapping ( link : chapters )
		if( hasLinkToBooks(chapters) ) {
			BooksEntity books1 = new BooksEntity();
			books1.setBookId( chapters.getBookId() );
			chaptersEntity.setBooks( books1 );
		} else {
			chaptersEntity.setBooks( null );
		}

	}
	
	/**
	 * Verify that Books id is valid.
	 * @param Books Books
	 * @return boolean
	 */
	private boolean hasLinkToBooks(Chapters chapters) {
		if(chapters.getBookId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}