/*
 * Created on 2019-03-15 ( Time 17:11:28 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package com.nit.order_library.web.common;

public interface ListItem {

	public String getValue();
	
	public String getLabel();
}
