/*
 * Created on 2021-09-27 ( Time 22:21:02 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.nit.order_library.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "prepayment"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="prepayment", catalog="niceorder" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="PrepaymentEntity.countAll", query="SELECT COUNT(x) FROM PrepaymentEntity x" )
} )
public class PrepaymentEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="prepayment_id", nullable=false)
    private Integer    prepaymentId ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="data", nullable=false, length=0)
    private String     data         ;

    @Column(name="use_yn", length=1)
    private String     useYn        ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Column(name="order_Id")
    private Integer    orderId      ;

	// "userId" (column "user_Id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="user_Id", referencedColumnName="user_id")
    private UserEntity user        ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PrepaymentEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setPrepaymentId( Integer prepaymentId ) {
        this.prepaymentId = prepaymentId ;
    }
    public Integer getPrepaymentId() {
        return this.prepaymentId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : data ( JSON ) 
    public void setData( String data ) {
        this.data = data;
    }
    public String getData() {
        return this.data;
    }

    //--- DATABASE MAPPING : use_yn ( CHAR ) 
    public void setUseYn( String useYn ) {
        this.useYn = useYn;
    }
    public String getUseYn() {
        return this.useYn;
    }

    //--- DATABASE MAPPING : updated_at ( DATETIME ) 
    public void setUpdatedAt( Date updatedAt ) {
        this.updatedAt = updatedAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    //--- DATABASE MAPPING : created_at ( DATETIME ) 
    public void setCreatedAt( Date createdAt ) {
        this.createdAt = createdAt;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }

    //--- DATABASE MAPPING : order_Id ( INT ) 
    public void setOrderId( Integer orderId ) {
        this.orderId = orderId;
    }
    public Integer getOrderId() {
        return this.orderId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setUser( UserEntity user ) {
        this.user = user;
    }
    public UserEntity getUser() {
        return this.user;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(prepaymentId);
        sb.append("]:"); 
        sb.append(data);
        sb.append("|");
        sb.append(useYn);
        sb.append("|");
        sb.append(updatedAt);
        sb.append("|");
        sb.append(createdAt);
        sb.append("|");
        sb.append(orderId);
        return sb.toString(); 
    } 

}
