<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2021-09-27 ( Time 22:21:02 ) -->

<div>

<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib tagdir="/WEB-INF/tags/util" prefix="util"%>
<%@ taglib tagdir="/WEB-INF/tags/display" prefix="display"%>


	<div class="container">
		<fieldset class="col-sm-12 bordure">
			<legend class="legende">prepayment</legend>
		
			<util:message message="${message}" messages="${messages}" />

			<table class="table table-striped">
				<thead>
					<tr>
						<th>prepayment.prepaymentId</th>
						<th>prepayment.data</th>
						<th>prepayment.useYn</th>
						<th>prepayment.updatedAt</th>
						<th>prepayment.createdAt</th>
						<th>prepayment.orderId</th>
						<s:url var="url_create" value="/prepayment/form"  />
						<th><a class="btn btn-info" href='${url_create}'>create</a></th>
					</tr>
				</thead>
				<tbody>
					<c:forEach items="${list}" var="prepayment">
						<tr>
							<td>${prepayment.prepaymentId}</td>
							<td>${prepayment.data}</td>
							<td>${prepayment.useYn}</td>
							<td><display:date value="${prepayment.updatedAt}" /></td>
							<td><display:date value="${prepayment.createdAt}" /></td>
							<td>${prepayment.orderId}</td>
							<s:url var="url_update" value="/prepayment/form/${prepayment.prepaymentId}"/>
							<td><a class="btn btn-info" href="${url_update}">edit</a></td>
						</tr>
					</c:forEach>
				</tbody>
			</table>
		</fieldset>
	</div>
</div>